- package.json
- srcs/app.tsx
- srcs/config/connectDB.tsx
- srcs/config/db_connect.tsx
- srcs/config/index.tsx
- srcs/controllers/exampleController.tsx
- srcs/controllers/index.tsx
- srcs/routes/index.tsx
> 구조 관련 예시 작성 및 임시 DB 추가

- .eslintrc.json
- .github/workflow/test.yml
- .gitignore
- __tests__/simple.test.tsx
- jest.config.js
- package-lock.json
- package.json
- srcs/app.tsx
- srcs/index.tsx
- srcs/routes/index.tsx
- tsconfig.json
> Git action test workflow 작성

- srcs/controllers/controller.getTeam.tsx
- srcs/controllers/index.tsx
- srcs/routes/index.tsx
-다른 팀원이 만든 컨트롤러를 참고하면서 각 구성요소가 무엇인지 찾아보는 중
resolved:#30
문제사항 기록
-포스트맨으로 요청시 404에러가 뜸 getUser는 정상작동함
-쿼리 값이 비어있는 경우 어떤 값이 반환되는지 확인해봐야함
> GET team/{teamId} 컨트롤러 작성

- srcs/swagger/controller/updateTeamState.tsx
- srcs/swagger/schema/team.tsx
- team schema 작성
- updateTeamState controller API 작성
resolved: #58
문제사항 기록
- 작성하다보니 team schema가 필요해서 updateTeamState 작성하는 김에 같이 했습니다.
- 일단 한글로 작성했는데 영어로 작성해야 하는거면 수정하겠습니다.
> feature: swagger에 team schema, updateTeamState controller API 문서 작성

- srcs/swagger/controller/addUser2Waitlist.tsx
- srcs/swagger/controller/removeUser2WaitList.tsx
- srcs/swagger/schema/waitlist.tsx
- Waitlist스키마 필요하여 작성
- POST /waitlist API문서 작성성
- DELETE /waitlist/{userId} API문서 작성
resolved: #47
문제사항 기록
- waitlist스키마 작성
- 스키마 수정전에  작성한  api들  수정필요(ex 파라미터이름)
> feature : swagger에 담당 API문서작성

- srcs/controllers/controller.getTeam.tsx
-query limit page가 둘 다 없을 때 전체 팀 데이터 값 반환 data: allTeams
-eslint 적용했음
resolved: #72
> GET /team API 반환 값 수정

- srcs/swagger/controller/creatGitRepo.tsx
-Swagger로 creatGitRepo API 문서 작성
resolved: #79
> docs: Swagger로 creatGitRepo API 문서 작성

- srcs/swagger/controller/addUser2Team.tsx
- srcs/swagger/controller/getUser.tsx
- srcs/swagger/schema/user.tsx
resolved:#62
- getUser 에러 처리 세분화 필요
=> 현재, 하나의 에러 코드로 모든 에러 처리 중
=> 발생할 수 있는 에러에 대한 조사 필요
- addUser2Team 도 마찬가지
> swagger API 문서 작성

- srcs/controllers/controller.addUser2Team.tsx
- srcs/controllers/controller.getUser.tsx
- srcs/models/model.user.tsx
- srcs/routes/index.tsx
resolved: #77 
- `addUser2Team` 컨트롤러 export 부분과 컨트롤러 index의 export 부분의 함수명이 매칭이 안되어 유저 추가 API 미작동 에러 발생
> [fix] 코드 , API 문서, 시퀀스 다이어그램 Naming 통일

- srcs/swagger/schema/waitlist.tsx
-user의 items type를 tpye로 작성된 부분 수정
resolved:#83
> fix : swagger의 waitlist모델 오타 수정

- srcs/lib/index.tsx
- srcs/lib/lib.Scheduler.tsx
- 인자로 (시작 요일 인덱스, 시작 시간, 시작 분, 반복 간격(초단위), 콜백 함수)를 받음
- 요일 인덱스는 '일', '월', '화', '수', '목', '금', '토' 순서로 0부터 6까지의 숫자
- 시작 시간은 0부터 23까지의 숫자
- 시작 분은 0부터 59까지의 숫자
- 반복 간격은 음수일 수 없고 24일을 넘어설 수 없음 (setTimeInterval 한계)
- 스케줄러를 종료시키는 함수를 반환함
resolved: #89 
참고자료 : [setTimeout과 setInterval을 이용한 호출 스케줄링](https://ko.javascript.info/settimeout-setinterval)
> feature: 스케줄러 기능 작성

- srcs/swagger/controller/getTeam.tsx
>  GET /team/{teamID} swagger 문서 작성

- srcs/controllers/controller.getTeam.tsx
- srcs/routes/index.tsx
-teamId를 teamID로 교체했다.
resolved: #71
> [fix] swagger문서, 시퀀스다이어그램, 코드의 명칭 일치시키기

- srcs/controllers/controller.inviteToRepo.tsx
- srcs/controllers/index.tsx
- srcs/routes/index.tsx
- srcs/swagger/controller/inviteToRepo.tsx
- req.body에 gitID와 gitLink를 받아 초대장을 발송
resolved: #61
> feature: git 초대장 발송 API 작성

- srcs/models/model.team.tsx
- srcs/swagger/schema/team.tsx
-팀을 설명하는 정보를 담는 explain 타입은 String
-팀을 설명하는 키워드를 담는 tag, 타입은 String 배열
resolved:#111
> 팀 스키마에 팀 설명, 팀 태그 추가

- srcs/controllers/controller.addUser2Waitlist.tsx
- srcs/controllers/controller.removeUser2WaitList.tsx
- srcs/swagger/controller/addUser2Waitlist.tsx
- srcs/swagger/controller/removeUser2WaitList.tsx
- post /waitlist 수정
- post/ waitlist api문서 수정
- delete/ waitlist api수정
- delete/ waitlist api문서 수정
resolved: #114
> Feat: User스키마에 deadline추가에 따라 api수정

- srcs/lib/index.tsx
- srcs/lib/lib.findAllUser.tsx
- srcs/lib/lib.findOneUser.tsx
resolved:#118
- findOneUser 함수 구현 (특정 유저 조회)
- findAllUser 함수 구현 (모든 유저 조회)
> 공통 라이브러리 작성 : 유저 조회 및 에러 처리

- srcs/controllers/controller.getTeam.tsx
resolved:123
allTeams 변수를  const에서 let으로 변경했습니다.
조건문은 필요 한 것 같아서 놔뒀습니다.
테스트 해봤는데 이상 없었습니다.
> getTeam API for문 개선

- srcs/controllers/controller.createGitRepo.tsx
- srcs/controllers/controller.inviteToRepo.tsx
- srcs/controllers/controller.updateTeamState.tsx
- srcs/controllers/index.tsx
- srcs/models/model.team.tsx
- ! 을 좀더 명확하게 변경(=== null|| ===undefined)
- update & find를 findOneAndUpdate 로 변경
- creatGitrepo 오타 수정
- 성공시 staus(200) 상태코드 추가
resolved: #125
> refactor : gitrepo/teamState 리팩토링

- srcs/lib/index.tsx
- srcs/lib/lib.findAllTeam.tsx
- srcs/lib/lib.findOneTeam.tsx
- 단일 팀/ 전체 팀 정보조회 라이브러리 작성
resolved: #136
> refactor: 팀 정보 조회 라이브러리 작성

- srcs/controllers/controller.addUser2Waitlist.tsx
- srcs/controllers/controller.removeUser2WaitList.tsx
- srcs/lib/index.tsx
- srcs/lib/lib.findOneWaitlist.tsx
- 공통모듈 이름을 잘못 지은걸 발견하여 수정 findOneWaitlist로 rename
resolved: #126
> refactor: 공통 모듈 이름 수정

- srcs/controllers/controller.addUser2Waitlist.tsx
- POST /waitlist api에 findOneUser[공통모듈] 적용
- 에러처리 코드 개선
-  map메소드와 include메소드 사용하여 user중복 대기 확인 로직 개선, 함수화하기
- 몽구스 메소드 형식 통일
resolved:#141
> refactor: post /waitlist 코드 개선

- srcs/controllers/controller.getWaitlist.tsx
- 랜덤 매칭 대기자들의 총인원 계산하는 로직에 내장 메소드 reduce사용하여 가독성 향상
resolved: #144
> refactor: get /waitlist api 리팩토링

- srcs/controllers/controller.createGitRepo.tsx
- srcs/controllers/controller.inviteToRepo.tsx
- 깃 저장소 코드 리팩토링
resolved: #156 
+) updateTeam API에서 현민님이 말씀해주신 옵셔널 체이닝으로 수정해봤었는데 updateData에 해당 값이 null이나 undefined으로 들어갈 경우 데이터베이스에서 해당 값이 null로 업데이트 되어버려서 쓸 수 없었습니다.
> refactor: 깃 저장소 관련 코드 리팩토링

- srcs/controllers/controller.addUser2Team.tsx
> addUser2team 컨트롤러 코드에 공통 라이브러리 함수 적용 및 리팩토링 작업 

- srcs/lib/lib.findAllTeam.tsx
> fix: findAllTeam 리턴 타입 변경

- srcs/controllers/controller.getTeam.tsx
>  getTeam API에 공통 모듈 적용및 리펙토링

- srcs/lib/index.tsx
- srcs/lib/lib.createNotionPage.tsx
resolved: #160 
- 매개변수를 teamID가 아닌 team 객체로 받는다면, 팀을 조회하는 비용을 줄일 수 있을 것으로 보입니다.
- 라이브러리 함수 예외 처리 관련 트러블 슈팅 => [링크](https://observant-colt-711.notion.site/d19a4f8683b74cc8b0df94774bad12ab)
> 노션 페이지 발급 라이브러리 함수 구현

- srcs/swagger/controller/inviteToRepo.tsx
> fix: invitetorepo 스웨거 문서 오타 수정

- @types/types.d.tsx
- srcs/models/model.team.tsx
> 데이터 타입 업데이트

- srcs/lib/lib.sendSlackMessage.tsx
- 인자 데이터타입을 string -> tTeam객체로 수정
resolved:#183
> refactor: 슬랙 메시지 발송 라이브러리 인자 수정

- @types/types.d.tsx
- srcs/models/model.user.tsx
- srcs/swagger/controller/getAllUser.tsx
- srcs/swagger/controller/getOneUser.tsx
- srcs/swagger/schema/user.tsx
> 유저 스키마에 유저의 과거 팀 리스트 필드를 추가

- srcs/controllers/controller.checkGitInvite.tsx
- srcs/controllers/controller.inviteToRepo.tsx
- srcs/controllers/index.tsx
- srcs/lib/lib.getGitName.tsx
- srcs/routes/index.tsx
- srcs/swagger/controller/checkGitInvite.tsx
- 사용자가 저장소에 초대되어있는지 확인
- 깃 저장소 이름만 가져오는 함수를 라이브러리로 분리
resolved: #187
> feat: 사용자가 저장소에 초대되어있는지 확인하는 API 구현

- .github/workflows/server-cd.yml
-  develoment에 push 될때 배포되도록 수정
resolved: #194
> env : test위해 cd수정

- srcs/index.tsx
> test를 위한 매칭 스케줄

- srcs/lib/lib.Scheduler.tsx
-스케줄러 시간대를 new Date()에서 한국기준으로 수정
resolved: #198
> fix: 스케줄러 시간대 한국 기준으로 수정

- srcs/controllers/controller.addUser2Team.tsx
- gitName도 받아서 User 수정하는 로직으로 수정
resolved: #204
> feature : front요청 - 팀 멤버 추가 api(addUser2Team) 수정

- .github/workflows/server-cd.yml
- appspec.yml
- deploy-server.sh
- ec2 instance t2.xlarge로 업그레이드
- ci/cd 의 배포 인스턴스도 새로운 인스턴스로 변경
- https 적용
- codedeploy 작업시에 인스턴스 자원 부족으로 중지되던 문제 인스턴스 업그레이드로 해결
resolved: #206
> environment: aws 인스턴스 업그레이드

- srcs/app.tsx
> CORS Origin에 테스트용 로컬 도메인 추가

- srcs/app.tsx
> 테스트를 위해 CORS Origin 모두 허용

- srcs/controllers/controller.inviteToRepo.tsx
- 퍼미션 타입으로 인해 발생한 깃 초대 에러 수정
resolved:#219
> hotfix: 깃 초대 에러 수정

- srcs/controllers/controller.inviteToRepo.tsx
- srcs/lib/lib.createGitRepo.tsx
- srcs/lib/lib.getGitName.tsx
> hotfix: 깃 관련 에러 로그 추가

- srcs/config/winston.tsx
> feat: 에러 로그 스택 추적

- srcs/lib/lib.Scheduler.tsx
> fix: 스케줄러 시간 서버 시간에 상관 없도록 수정

- .github/workflows/server-cd.yml
- cd - master 브랜치에 push했을때 동작하도록 수정
resolved: #229
> env : CI/CD 동작 시점 수정

- .github/workflows/dev-server-cd.yml
> Dev 서버 CI/CD 파이프라인 설정

- srcs/lib/lib.Matcher.tsx
- srcs/models/model.team.tsx
> feat: teamName short

- __tests__/simple.test.tsx
- srcs/app.tsx
- srcs/controllers/controller.addUser2Waitlist.tsx
- srcs/index.tsx
- srcs/lib/lib.Matcher.tsx
- srcs/lib/lib.sendSlackMessage.tsx
- srcs/models/model.user.tsx
resolved: #237 
문제상황
- git repo가 생성되지 않았음
> feature: matchingDB 개인으로 변경

- srcs/lib/lib.Matcher.ts
In error fixing in sendSlackMessage
> fixing process

- srcs/lib/lib.Matcher.ts
> Development 2.1.1
